[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["nodemailer"]
  included_files = [".env"]

[dev]
  framework = "#auto"
  targetPort = 3000
  port = 8888
  publish = "dist"
  functions = "netlify/functions"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
